### PR TITLE
Added core query expression evaluation logic (and linted stuff)

### LINKED ISSUE #253: Add query expression evaluation logic to @pigi/core
The Generalized Plasma Specification describes a method for [querying the client](http://spec.plasma.group/en/latest/src/03-client/state-queries.html) with special ["query expressions"](http://spec.plasma.group/en/latest/src/03-client/query-expressions.html). We need to implement the basic query expression logic and add tests to ensure that filters will work as expected.

### PR DESCRIPTION
**Pull request by kfichter**
- [x] I have read and understood the [Plasma Group Contributing Guide and Code of Conduct](https://github.com/plasma-group/pigi/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

------------------------------------------------------------------------

Fixes #253 

## Description
This PR looks like a lot of content but it really isn't. I got obsessive and started linting everything halfway through... sorry.

Main content is in `expressions.ts`, where I've added a system for evaluating [query expressions](http://spec.plasma.group/en/latest/src/03-client/query-expressions.html) for [state queries](http://spec.plasma.group/en/latest/src/03-client/state-queries.html).

### CODE REVIEW

**Comment by kfichter** [comment]
@karlfloersch hmm I'm not sure I follow - the expressions seem relatively general purpose and state query stuff will depend on expression stuff being merged. What are the benefits of waiting to merge later in your opinion?

**Comment by kfichter** [comment]
As a note, the process for executing state queries is [specified in detail here](https://docs.plasma.group/projects/spec/en/latest/src/03-client/state-queries.html) and makes use of expressions as implemented in this PR.

**Comment by karlfloersch** [comment]
> @karlfloersch hmm I'm not sure I follow - the expressions seem relatively general purpose and state query stuff will depend on expression stuff being merged. What are the benefits of waiting to merge later in your opinion?

Ah yeah I was saying that because the state querying is an isolated feature, we can keep this in a `state-query` branch which is merged in once we have state manager & state query implemented. Reduces the amount of orphaned code.

**Comment by kfichter** [comment]
Got it, makes sense 👍

**Comment by kfichter** [comment]
@karlfloersch - I just fixed the PR :+1:

**Pull request closed without merging**
