### PR TITLE
Docs updates for plasma and vyper-js

### LINKED ISSUE #78: Add a page that explains what invalid withdrawals are and how they're challenged
## Exits 101

Withdrawals of funds from the plasma chain ("exits") are a core part of plasma. In effect, each exit is a claim about the current state of the plasma chain along with an action as a result of that claim. For example, the claim might be "I claim that I had 100 ETH on the plasma chain at time T" and the action might be "I want to withdraw 100 ETH". 

Unfortunately it's not simple for the plasma chain smart contract to tell which exits are valid and which aren't. Usually, we end up having to use something called a "claim-challenge" game whereby an exit can be blocked with a challenge that proves the claim is invalid. 

## Tasks

We need to add a documentation page to the [Plasma Group docs](https://github.com/plasma-group/pigi/tree/master/packages/docs/src/pg) that explains what invalid withdrawals are and how challenges are used to resolve them. We basically just want a very intuitive article (diagrams would be great!) that explains in a nutshell:

1. How withdrawals work.
2. Why certain withdrawals can be invalid.
3. How challenges can be used to prevent invalid withdrawals.

## Resources

Withdrawals can be a fairly complex subject to write about! Feel free to reach out to me if you'd like to hop on a call to go through how withdrawals work in detail. You'll become a plasma expert in no time! :-)

### PR DESCRIPTION
**Pull request by aerophile**
- [X ] I have read and understood the [Plasma Group Contributing Guide and Code of Conduct](https://github.com/plasma-group/pigi/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

------------------------------------------------------------------------

Fixes #78  #42  #184 
Suggestions/edits to improve are welcome, will be happy to improve the docs based on feedback.

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
@aerophile Pretty pleased with this PR, I made some small grammar and syntax changes here - https://github.com/aerophile/pigi/pull/2

Also, this looks like it's just two of the tasks, which is fine, as I have PRs from other contributors for the other task.

**Comment by aerophile** [comment]
@ChrisChinchilla  Thank you for your reviews and improvements in grammar and syntax, much appreciated. I've accepted and merged your changes to my forked repository. Should I send another pull request (with your changes) to the pigi repo ?

**Comment by ChrisChinchilla** [comment]
@aerophile Nope, should all get reflected in that PR, will review for final checks later

**Comment by ChrisChinchilla** [comment]
OK, from your PR I'm picking the work for #78 and #184 so will pay out 2/3 of the bounty and resolve getting the PRs merged with the Plasma group team and final polish.

**Comment by kfichter** [comment]
Heyo! We're doing some repo overhauls and our docs are moving around. We're going to close this PR until we can find the right place to put this information.

**Pull request closed without merging**
